### ISSUE TITLE
Getting Crash after logging in with Twitter

### ISSUE THREAD

**Issue by edkim** [firebase/ios-swift-chat-example#13]
FireChat-Swift[46963:5394333] AuthData twitter:42065237
fatal error: unexpectedly found nil while unwrapping an Optional value

In MessagesViewController: setupAvatarImage()
let image = UIImage(data: NSData(contentsOfURL: url!)!) //Crashes on this line

This is using the iOS Simulator.

**Comment by katfang** [comment]
Hi! This happens when the URL of an avatar no longer points to an image. This should be fixed! Anything without an image should get a colored circle as a default image.
