### ISSUE TITLE
Outdated JSQMessagesViewController

### ISSUE THREAD

**Issue by aaronz8** [firebase/ios-swift-chat-example#14]
There have been many breaking updates to the JSQMessagesViewController code. I just went through the process of figuring out some of the changes, but this thread seems to cover the important ones I got stuck on:

https://github.com/jessesquires/JSQMessagesViewController/issues/713

I'm not sure if anyone else is working on an update already, but if not I'll try to do it. Disclaimer... this is my first week programming for iOS.

**Comment by frankgumeta** [comment]
HI!, I'd like to help you. But I'm not shure about your concern. Don't give up. I have 5 years With Obj-c & 4 months with swift and had troubles just with the implementation xD

**Comment by aaronz8** [comment]
:) thanks a lot!

**Comment by davideast** [comment]
@aaronz8 Thanks for letting us know it's outdated. I don't think we're going to upgrade since we have the version we need checked into source. Let me know if it's blocking you though!
