### ISSUE TITLE
How to get my own firebase URL?

### ISSUE THREAD

**Issue by dddu88** [firebase/ios-swift-chat-example#15]
In the setup section, the first step is Create a new Firebase, what does that mean? I created a firebase account, and see it is about web hosting, do I need to deploy a website on firebase to run the chat example? I just need to see the chat example working in simulator, that is all I need, how to get my own firebase URL?

Thanks
Dave

**Comment by mimming** [comment]
Hi Dave!

If you signed up for a Firebase account, you already have a Firebase. We create one automatically when you register.  You can see it, and create new ones, from your Firebase Dashboard at https://www.firebase.com/account/
