### ISSUE TITLE
trouble getting the demo working with twitter login

### ISSUE THREAD

**Issue by mypark** [firebase/ios-swift-chat-example#17]
I'm getting the following error with the demo - using my twitter consumer key as the app id, as well as leaving it as the original in the source code.

in Step 2 of the TwitterAuthHelper, requestTwitterCredentials

Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed. (NSURLErrorDomain error -1012.)" UserInfo=0x17426d940 {NSErrorFailingURLStringKey=https://api.twitter.com/oauth/access_token

**Comment by holgersindbaek** [comment]
+ 1. @mypark Did you ever resolve this?

**Comment by holgersindbaek** [comment]
Seems like people are also having the problem here: 

https://groups.google.com/forum/#!topic/firebase-talk/GIaO7rEVfos

No one else is experiencing this? Any hints on what to do going forward?

**Comment by jdimond** [comment]
The error code is -1012 is used for HTTP status codes 401, which indicates that authentication failed. Make sure to
a) Use the correct twitter API key in the code.
b) Set the correct API key/secret in Firebase Forge.
c) You are using the correct credentials for your Twitter account

**Comment by drscodemonkey** [comment]
Same error here. Verified the API key and secret several times, even regenerated them. STILL won't connect.

What's the trick here? A step or "gotcha" must have been left out.

**Comment by theparkland** [comment]
Same here... What the callback URL supposed to be on the Twitter side?  Maybe that's the missing link for us having trouble.
