### ISSUE TITLE
Opening messaging page on simulator 

### ISSUE THREAD

**Issue by SkylerBenge** [firebase/ios-swift-chat-example#18]
After connecting my twitter account in settings, and changing the firebase url to my new url after I click on login with twitter nothing happens. It's not giving any errors so I'm not sure what's going on.

**Comment by jdimond** [comment]
The example doesn't log errors. If you add logging in LoginViewController you will likely get the error message. You will also need to configure twitter authentication in the Firebase console and in the Twitter developer console.

**Comment by huyouare** [comment]
There's more detailed instructions here: https://github.com/firebase/ios-swift-chat-example/pull/16

**Comment by davideast** [comment]
@SkylerBenge I'm closing this unless you feel it needs to be reopened.

As Jonny said you need to get secret and client keys from Twitter and register them in the Dashboard.
