### ISSUE TITLE
How to install JSQMessagesViewController with cocoapods?

### ISSUE THREAD

**Issue by jerry-sjtu** [firebase/ios-swift-chat-example#19]
I tried to install JSQMessagesViewController with cocoapods and use swift to call it, then I got some problems which I cannot solve by myself. Here is the problem information:
http://stackoverflow.com/questions/29692448/how-to-import-jsqmessagesviewcontroller-in-swift

Can you help me to fix this problem? Thanks!

**Comment by davideast** [comment]
Hello! I think this goes beyond the scope of this repo. Good luck in S/O endeavors.

**Comment by guillosaracco** [comment]
@jerry-sjtu, I know this issue is closed, but did you figure it out?
