### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by danshev** [firebase/ios-swift-chat-example#20]
Due to slight changes with Swift / xCode, need to ...

 **Change:**

    func application(application: UIApplication!,didFinishLaunchingWithOptions launchOptions: NSDictionary!) -> Bool {

**To:**

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

You'll also need to accept all the recommended fixes, mostly dealing with changes to how Swift handles casting.

**Comment by davideast** [comment]
Fixed in recent version.
