### ISSUE TITLE
Shows an error XCtest/Xctest.h not found

### ISSUE THREAD

**Issue by jogikushal** [firebase/ios-swift-chat-example#25]
<img width="773" alt="screen shot 2015-07-04 at 1 20 18 pm" src="https://cloud.githubusercontent.com/assets/9759236/8508841/921b6292-224f-11e5-8ecb-5d7f25af1021.png">

**Comment by davideast** [comment]
Can you provide more information?

**Comment by jogikushal** [comment]
Actually, I figured out this issue. When I added the framework to my project from this example it showed me errors .Then,  I had to install the cocoapod for JSQMessages.
