### ISSUE TITLE
firebase pod install failed!

### ISSUE THREAD

**Issue by PrajeetShrestha** [firebase/ios-swift-chat-example#26]
Downloading dependencies
Installing Firebase (2.3.3)

[!] Error installing Firebase
[!] /Applications/XAMPP/xamppfiles/bin/curl -f -L -o /Volumes/DATA/PROJECTS/SwiftFire/Pods/Firebase/file.zip https://cdn.firebase.com/ObjC/Firebase.framework-2.3.3.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

curl: (60) SSL certificate problem: unable to get local issuer certificate

More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"

 of Certificate Authority (CA) public keys (CA certs). If the default

 bundle file isn't adequate, you can specify an alternate file

 using the --cacert option.

If this HTTPS server uses a certificate signed by a CA represented in

 the bundle, the certificate verification probably failed due to a

 problem with the certificate (it might be expired, or the name might

 not match the domain name in the URL).

If you'd like to turn off curl's verification of the certificate, use

 the -k (or --insecure) option.

**Comment by jdimond** [comment]
This is likely an issue with your machine and it seems your CAs are a bit messed up. You can check this by opening https://cdn.firebase.com/ObjC/Firebase.framework-2.3.3.zip in the browser. If that fails you will need to fix the CAs on your machine.

**Comment by pomin** [comment]
I can download zip file by https://cdn.firebase.com/ObjC/Firebase.framework-2.3.3.zip, 
but I got this error:
curl: (35) Unknown SSL protocol error in connection to cdn.firebase.com:-36

It's any suggestions for this?

**Comment by vonnyfly** [comment]
I also have this problem. Could you give any suggestion?

**Comment by jdimond** [comment]
Try downloading the framework manually on the console with
```
curl -O https://cdn.firebase.com/ObjC/Firebase.framework-2.4.1.zip
```

If that fails, then it's likely a problem with your machine and SSL setup (e.g. if you are on a public wifi with a captive portal, root CAs are messed up etc.)

**Comment by swinghu** [comment]
If that fails, then it's likely a problem with your machine and SSL setup (e.g. if you are on a public wifi with a captive portal, root CAs are messed up etc.)


How to ?

**Comment by swinghu** [comment]
when execute:curl -v https://cdn.firebase.com, errors:

* Rebuilt URL to: https://cdn.firebase.com/
* Hostname was NOT found in DNS cache
*   Trying 103.245.222.249...
* Connected to cdn.firebase.com (103.245.222.249) port 443 (#0)
* Unknown SSL protocol error in connection to cdn.firebase.com:-36
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to cdn.firebase.com:-36

**Comment by senseluo** [comment]
still facing the same problem
