### ISSUE TITLE
Wrong top inset when pushing controller

### ISSUE THREAD

**Issue by pash3r** [firebase/ios-swift-chat-example#45]
Hello! When we push our chatController we get wrong top inset (our chat is under navBar), when keyboard appears all insets gets correct and after keyboard dismiss too. But if I present chatController modally it works fine. Maybe I don't understand something. You can reproduce this issue in the example app, just change `presentViewController:` to `pushViewController:` :(

I use the develop branch because master does not want to work with iOS 9+ and Xcode 7.3.1.

**Comment by abehaskins** [comment]
Hey, sadly we're not making any changes / bug-fixes to this legacy example any more. Check out [FriendlyChat for iOS](https://github.com/firebase/friendlychat) for a more up-to-date example that shouldn't have this issue.
