### ISSUE TITLE
Unknown type name 'Firebase' in TwitterAuthHelper.h

### ISSUE THREAD

**Issue by lsantamaria** [firebase/ios-swift-chat-example#47]
I just downloaded the code, installed the pod and opened project from terminal.

I'm getting the following error in TwitterAuthHelper.m class:

 "Unknown type name 'Firebase'"

in this line: 
@property (strong, nonatomic) Firebase *ref;

Is someone getting the same error?

Thanks in advance

**Comment by abehaskins** [comment]
This is a sample for the legacy Firebase SDK. Seems like you're trying to use the new SDK and getting an error. I would suggest building off of a newer sample since we're no longer supporting this sample.
